#!/bin/bash                                                                                                                             
# Copyright 2017 EugeneLab
# 
# aac2mp3
# 
# Convert a sound file format 'amr' to 'mp3' with a low bitrate of 16k
# 
# Usage:
# aac2mp3 [file.aac]

if [ -z "$1" ]; then                                                                                                                    
    echo 'file.aac?'                                                                                                         
    exit                                                                                                                                
fi                                                                                                                                      

input=$1
name=${input%.amr}
output=$name.mp3

ffmpeg -i $input  -ab 16k $output
