#!/bin/bash                                                                                                                             
# Copyright 2015-2018 EugeneLab
# 
# get: downloading files from the server to the same directory on the local machine
# 


dir=`pwd`
last=`basename $dir`
pattern="/home/$last"

if [ $dir = $pattern ]; then
	point=$last
else	
    point=$USER
fi

remote="$point:$dir"
local=$dir/*

echo "local: $local"
echo "remote: $remote"

rsync -zuthvr --del --exclude=.*  --progress  $remote $local 

