#!/usr/bin/env ruby
# Copyright 2011 EugeneLab   

require 'rubygems'
require 'rake'

dir = ARGV[0] || File.expand_path(".")
FileList.new(dir+"/*").each do |path|
  name = File.basename(path)
  puts name
end
