#!/bin/bash                                                                                                                             
# list of points
# Copyright 2010 EugeneLab                                                                                                              

ls -1 /home
