#!/bin/bash                                                                                                                             
# Copyright 2014-2018 EugeneLab
# 
# put: uploading files from the current local directory to the same directory on the server
# 


dir=`pwd`
last=`basename $dir`
pattern="/home/$last"

if [ $dir = $pattern ]; then
	point=$last
else	
    point=$USER
fi

remote="$point:$dir"
local=$dir/*

echo "local: $local"
echo "remote: $remote"

rsync -lzuogthvr --delete-after  --exclude=.*  --progress  $local $remote

