#!/bin/bash                                                                                                                             
# Copyright 2017 EugeneLab
# 
# tram
# version: 1
# created: 2017-02-23
# updated: 2017-02-23
# 
# Start tram application on localhost 
# 

cd ~/tram
rails s -p 3003

